In [1]:
import pandas as pd
import numpy as np
from scipy import stats
import re

# Question 1

## Import Cities and NHL Dataset

In [41]:
nhl_df = pd.read_csv('assets/nhl.csv')

In [42]:
#nhl_df.head()

In [43]:
nhl_df = nhl_df[nhl_df['year'] == 2018]

In [44]:
#nhl_df.head()

In [45]:
cities_df = pd.read_html('assets/wikipedia_data.html')[1]

In [46]:
#cities_df.head()

In [47]:
cities_df.rename({'Population (2016 est.)[8]': 'Population'}, axis=1, inplace=True)

In [48]:
new_nhl = cities_df[['Metropolitan area', 'NHL']]

In [49]:
new_nhl['LName'] = new_nhl['NHL'].apply(lambda x: re.findall('[A-Z][a-z]+', x))

C:\Users\Mann\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [50]:
new_nhl = new_nhl.explode(column='LName').drop('NHL', axis=1).dropna()

In [51]:
new_nhl.rename({'LName': 'team_LName'}, axis=1, inplace=True)

In [52]:
#new_nhl.head()

In [53]:
nhlteams_index = new_nhl['Metropolitan area'].unique()

In [54]:
nhl_df['team_LName'] = nhl_df['team'].apply(lambda x: re.findall('.+\s(\w+)\*?', x)[-1])

In [55]:
#nhl_df.head()

In [56]:
nhl_cities = nhl_df.merge(new_nhl, right_on='team_LName', left_on='team_LName')

In [58]:
#nhl_cities.head()

In [59]:
nhl_cities['W'] = nhl_cities['W'].astype(int)
nhl_cities['L'] = nhl_cities['L'].astype(int)

In [60]:
nhl_cities['W/L_%'] = nhl_cities['W'] / (nhl_cities['L'] + nhl_cities['W'])

In [61]:
#nhl_cities.head()

In [62]:
nhl_cities_merged = nhl_cities.groupby('Metropolitan area').agg({'W/L_%': 'mean'}).sort_index()

In [63]:
#cities_df.head()

In [64]:
q1 = nhl_cities_merged.merge(cities_df[['Metropolitan area', 'Population']], on='Metropolitan area')

In [65]:
q1 = q1.set_index('Metropolitan area').loc[nhlteams_index]

In [66]:
q1.head()

                           W/L_% Population
Metropolitan area
New York City           0.518201   20153634
Los Angeles             0.622895   13310447
San Francisco Bay Area  0.625000    6657982
Chicago                 0.458333    9512999
Dallas–Fort Worth       0.567568    7233323

In [67]:
cities_df=cities_df.iloc[:-1,[0,3,5,6,7,8]]

In [68]:
cities_df

,Metropolitan area,Population,NFL,MLB,NBA,NHL
0,New York City,20153634,GiantsJets[note 1],YankeesMets[note 2],KnicksNets,RangersIslandersDevils[note 3]
1,Los Angeles,13310447,RamsChargers[note 4],DodgersAngels,LakersClippers,KingsDucks
2,San Francisco Bay Area,6657982,49ersRaiders[note 6],GiantsAthletics,Warriors,Sharks[note 7]
3,Chicago,9512999,Bears[note 8],CubsWhite Sox,Bulls[note 9],Blackhawks
4,Dallas–Fort Worth,7233323,Cowboys,Rangers,Mavericks,Stars
5,"Washington, D.C.",6131977,Redskins,Nationals[note 10],Wizards[note 11],Capitals
6,Philadelphia,6070500,Eagles,Phillies[note 12],76ers,Flyers[note 13]
7,Boston,4794447,Patriots[note 14],Red Sox[note 15],Celtics,Bruins
8,Minneapolis–Saint Paul,3551036,Vikings,Twins,Timberwolves,Wild[note 16]
9,Denver,2853077,Broncos,Rockies,Nuggets[note 17],Avalanche[note 18]
10,Miami–Fort Lauderdale,6066387,Dolphins,Marlins,Heat,Panthers
11,Phoenix,4661537,Cardinals,Diamondbacks,Suns,Coyotes
12,Detroit,4297617,Lions,Tigers[note 20],Pistons[note 21],Red Wings
13,Toronto,5928040,— [note 22],Blue Jays,Raptors[note 23],Maple Leafs
14,Houston,6772470,Texans[note 24],Astros,Rockets,—
15,Atlanta,5789700,Falcons,Braves,Hawks,[note 25]
16,Tampa Bay Area,3032171,Buccaneers,Rays,—,Lightning
17,Pittsburgh,2342299,Steelers,Pirates,[note 27],Penguins[note 28]
18,Cleveland,2055612,Browns[note 29],Indians[note 30],Cavaliers[note 31],[note 32]
19,Seattle,3798902,Seahawks,Mariners,[note 33],[note 34]
20,Cincinnati,2165139,Bengals,Reds[note 35],[note 36],—
21,Kansas City,2104509,Chiefs,Royals[note 37],[note 38],[note 39]
22,St. Louis,2807002,[note 40],Cardinals[note 41],[note 42],Blues[note 43]
23,Baltimore,2798886,Ravens[note 45],Orioles[note 46],[note 47],—
24,Charlotte,2474314,Panthers,—,Hornets[note 49],—
25,Indianapolis,2004230,Colts,[note 50],Pacers[note 51],—
26,Nashville,1865298,Titans,—,—,Predators
27,Milwaukee,1572482,[note 53],Brewers[note 54],Bucks,—
28,New Orleans,1268883,Saints,—,Pelicans[note 55],—
29,Buffalo,1132804,Bills[note 56],[note 57],[note 58],Sabres
30,Montreal,4098927,—,[note 59],—,Canadiens
31,Vancouver,2463431,—,—,[note 60],Canucks
32,Orlando,2441257,—,—,Magic,—
33,Portland,2424955,—,—,Trail Blazers,—
34,Columbus,2041520,—,—,—,Blue Jackets
35,Calgary,1392609,—,—,—,Flames
36,Ottawa,1323783,—,—,—,Senators
37,Edmonton,1321426,—,—,—,Oilers
38,Salt Lake City,1186187,—,—,Jazz,—
39,Winnipeg,778489,—,—,—,Jets[note 61]
40,San Diego,3317749,[note 62],Padres,[note 63],—
41,San Antonio,2429609,[note 64],—,Spurs,—
42,Sacramento,2296418,—,—,Kings,—
43,Las Vegas,2155664,[note 6],—,—,Golden Knights
44,Jacksonville,1478212,Jaguars,—,—,—
45,Oklahoma City,1373211,—,—,Thunder[note 68],—
46,Memphis,1342842,[note 69],—,Grizzlies,—
47,Raleigh,1302946,—,—,—,Hurricanes
48,Green Bay,318236,Packers,—,—,—
49,Hamilton,747545,—,—,—,[note 71]
50,Regina,236481,—,—,—,—

In [72]:
q1['Population'] = q1['Population'].astype(np.float)

In [73]:
stats.pearsonr(q1['W/L_%'], q1['Population'])

(0.012486162921209909, 0.9497182859911791)